[package]
name = "mixed-dependencies"
version = "0.1.0"
authors = ["Stefan Lau <github@stefanlau.com>"]

[dependencies]
brotli = "1.0"
base64 = "0.6"
getopts = { git = "https://github.com/rust-lang-nursery/getopts.git" }
